# Generated by Django 4.2.5 on 2023-11-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
        migrations.AddField(
            model_name='quote',
            name='categories',
            field=models.ManyToManyField(related_name='quotes', to='quote.category'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
